name: S3 Upload

on:
  workflow_dispatch:
    inputs:
      fileName:
        description: 'File name'
        required: true
        default: 'test.sql'

jobs:
  upload:
    name: Upload to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          aws s3 cp --region ap-northeast-1 test.sql s3://$BUCKET_NAME/${{ github.event.inputs.filename }}